substitutions:
  _SERVICE_NAME: "ubio-app"
  _REGION: "us-central1"
  _IMAGE_NAME: "practice-app"
  _REPO: "crytoapp"

steps:

  - name: 'gcr.io/$PROJECT_ID/sonar-scanner:latest'
    entrypoint: 'bash'
    secretEnv: ['SONAR_TOKEN'] # This must match the 'env' name below
    args:
      - '-c'
      - |
        sonar-scanner \
          -Dsonar.login=$$SONAR_TOKEN \
          -Dsonar.host.url=https://sonarcloud.io \
          -Dsonar.qualitygate.wait=true 
    id: 'quality-gate'


  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', '${_REGION}-docker.pkg.dev/$PROJECT_ID/${_REPO}/${_IMAGE_NAME}:$COMMIT_SHA', '.']
    id: 'build-image'
    waitFor: ['quality-gate']


  - name: 'aquasec/trivy:latest'
    args: ['image', '--severity', 'HIGH,CRITICAL', '--exit-code', '1', '${_REGION}-docker.pkg.dev/$PROJECT_ID/${_REPO}/${_IMAGE_NAME}:$COMMIT_SHA']
    id: 'security-gate'
    waitFor: ['build-image']


  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', '${_REGION}-docker.pkg.dev/$PROJECT_ID/${_REPO}/${_IMAGE_NAME}:$COMMIT_SHA']
    id: 'push-image'
    waitFor: ['security-gate']


  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: 'gcloud'
    args:
      - 'run'
      - 'deploy'
      - '${_SERVICE_NAME}'
      - '--image=${_REGION}-docker.pkg.dev/$PROJECT_ID/${_REPO}/${_IMAGE_NAME}:$COMMIT_SHA'
      - '--region=${_REGION}'
      - '--no-traffic'      
      - '--tag=green'       
      - '--port=8080'
    id: 'deploy-green'
    waitFor: ['push-image']


availableSecrets:
  secretManager:
  - versionName: projects/$PROJECT_ID/secrets/sonar/versions/latest
    env: 'SONAR_TOKEN'

options:
  logging: CLOUD_LOGGING_ONLY