# ============================================
# GOOGLE CLOUD BUILD CONFIGURATION
# CI/CD pipeline for ubioworo-project
# ============================================

substitutions:
  _SERVICE_NAME: "ci-cd-practice-app"     
  _REGION: "us-central1"                  
  _IMAGE_NAME: "practice-app"             
  _REPO: "crytoapp"                  

steps:
  # ------------------------------
  # STEP 1: PRINT BUILD INFO
  # ------------------------------
  - name: 'ubuntu'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        echo "🚀 STARTING CI/CD PIPELINE"
        echo "=========================="
        echo "Project: $PROJECT_ID"
        echo "Commit: $COMMIT_SHA"
        echo "Branch: $BRANCH_NAME"
        echo "Service: ${_SERVICE_NAME}"
        echo "Image: ${_REGION}-docker.pkg.dev/$PROJECT_ID/${_REPO}/${_IMAGE_NAME}:$COMMIT_SHA"
        echo ""

  # ------------------------------
  # STEP 2: INSTALL DEPENDENCIES & RUN TESTS
  # ------------------------------
  - name: 'node:18-alpine'
    entrypoint: 'sh'
    args:
      - '-c'
      - |
        echo "📦 Installing dependencies..."
        cd src
        npm ci
        echo "✅ Dependencies installed"
        echo ""
        echo "🧪 Running tests..."
        npm test
        echo "✅ Tests passed"

  # ------------------------------
  # STEP 3: BUILD DOCKER IMAGE
  # ------------------------------
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'build'
      - '-f'
      - 'Dockerfile'
      - '-t'
      - '${_REGION}-docker.pkg.dev/$PROJECT_ID/${_REPO}/${_IMAGE_NAME}:$COMMIT_SHA'
      - '-t'
      - '${_REGION}-docker.pkg.dev/$PROJECT_ID/${_REPO}/${_IMAGE_NAME}:latest'
      - '.'
    id: 'build'

  # ------------------------------
  # STEP 4: PUSH TO ARTIFACT REGISTRY
  # ------------------------------
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'push'
      - '${_REGION}-docker.pkg.dev/$PROJECT_ID/${_REPO}/${_IMAGE_NAME}:$COMMIT_SHA'
    id: 'push'
    waitFor: ['build']

  # ------------------------------
  # STEP 5: DEPLOY TO CLOUD RUN
  # ------------------------------
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: 'gcloud'
    args:
      - 'run'
      - 'deploy'
      - '${_SERVICE_NAME}'
      - '--image=${_REGION}-docker.pkg.dev/$PROJECT_ID/${_REPO}/${_IMAGE_NAME}:$COMMIT_SHA'
      - '--region=${_REGION}'
      - '--platform=managed'
      - '--allow-unauthenticated'
      - '--port=8080'
      - '--set-env-vars=ENV=production,COMMIT_HASH=$COMMIT_SHA,DEPLOYED_VIA=cloud-build'
      - '--memory=256Mi'
      - '--cpu=1'
      - '--min-instances=0'
      - '--max-instances=3'
    id: 'deploy'
    waitFor: ['push']

  # ------------------------------
  # STEP 6: PRINT DEPLOYMENT INFO
  # ------------------------------
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        echo ""
        echo "🎉 DEPLOYMENT SUCCESSFUL!"
        echo "========================"
        echo ""
        echo "Service URL:"
        gcloud run services describe ${_SERVICE_NAME} \
          --region=${_REGION} \
          --platform=managed \
          --format="value(status.url)"
        echo ""
        echo "View recent logs with:"
        echo "   gcloud logging read \"resource.type=cloud_run_revision AND resource.labels.service_name=${_SERVICE_NAME}\" --limit=10"
        echo ""
        echo "Service details:"
        echo "   gcloud run services describe ${_SERVICE_NAME} --region=${_REGION}"

# ------------------------------
# ARTIFACTS - Docker images
# ------------------------------
images:
  - '${_REGION}-docker.pkg.dev/$PROJECT_ID/${_REPO}/${_IMAGE_NAME}:$COMMIT_SHA'
  - '${_REGION}-docker.pkg.dev/$PROJECT_ID/${_REPO}/${_IMAGE_NAME}:latest'

# ------------------------------
# OPTIONS - Default Cloud Logging & service account
# ------------------------------
options:
  logging: CLOUD_LOGGING_ONLY
  machineType: 'E2_HIGHCPU_8'
  dynamicSubstitutions: true


# ------------------------------
# TIMEOUT - Maximum build time (1 hour)
# ------------------------------
timeout: 3600s
